export const pricingPlans = [
  {
    id: "free",
    name: "Free",
    price: "$0",
    period: "/month",
    description: "For getting started with CanvasX.",
    badge: null,
    features: [
      "2 Projects",
      "5 Screens per project",
      "3 Themes",
      "10 AI generations/month",
    ],
    buttonVariant: "outline" as const,
    polarProductId: null,
  },
  {
    id: "pro",
    name: "Pro",
    price: "$6",
    period: "/month",
    description: "For creators who need more flexibility.",
    badge: "Most popular",
    features: [
      "6 Projects",
      "10 Screens per project",
      "15 Themes",
      "100 AI generations/month",
    ],
    buttonVariant: "default" as const,
    highlighted: true,
    polarProductId: process.env.NEXT_PUBLIC_POLAR_PRO_PRODUCT_ID,
  },
  {
    id: "unlimited",
    name: "Unlimited",
    price: "$20",
    period: "/month",
    description: "For power users with bigger workflows.",
    badge: null,
    features: [
      "Unlimited Projects",
      "Unlimited Screens",
      "All 22 Themes",
      "Unlimited AI generations",
    ],
    buttonVariant: "outline" as const,
    polarProductId: process.env.NEXT_PUBLIC_POLAR_UNLIMITED_PRODUCT_ID,
  },
];
